// ─────────────────────────────────────────────────────────────────────────────
// ALL SHARED DATA — Bayelsa State Accountability Tracker
// ─────────────────────────────────────────────────────────────────────────────

// ── CABINET / OFFICIALS ──────────────────────────────────────────────────────
// Data sourced from Bayelsa State Govt press releases, BSIEC, NigeriaGalleria,
// LinkedIn profiles, and local journalism. Marked [UNVERIFIED] where uncertain.
// Fit scores are editorial assessments based on published credentials vs. role requirements.

export const OFFICIALS = [
  {
    id: 1,
    name: 'Nathaniel Ogaraku',
    position: 'Secretary to the State Government (SSG)',
    portfolio: 'Administration',
    icon: '🏛',
    tier: 'executive',
    fitScore: 72,
    fitLabel: 'QUALIFIED',
    education: 'Law background; senior civil servant',
    yearsRelevant: 20,
    background: 'Career civil servant with long tenure in Bayelsa state administration. Served across multiple administrations. Deep institutional knowledge of state bureaucracy.',
    requiredProfile: 'Strong public administration, legal, or governance background. Must coordinate all ministries and manage the civil service.',
    strengths: ['Long institutional experience', 'Knows the civil service machinery', 'Continuity across administrations'],
    concerns: [],
    verified: true,
    source: 'Bayelsa State Govt; Vanguard',
  },
  {
    id: 2,
    name: 'Sir Jonathan Obuebite',
    position: 'Commissioner for Finance',
    portfolio: 'Finance',
    icon: '💰',
    tier: 'commissioner',
    fitScore: 78,
    fitLabel: 'QUALIFIED',
    education: 'Accountancy / Finance background; chartered accountant credentials reported',
    yearsRelevant: 15,
    background: 'Has financial management and accountancy background. Overseeing a ₦380B state budget and FAAC/derivation receipts management.',
    requiredProfile: 'Must have economics, finance, or accounting credentials with public financial management experience. Oversees IGR, FAAC, derivation funds, and budget execution.',
    strengths: ['Finance/accounting professional background', 'Experience in public sector finance'],
    concerns: ['IGR has stalled at ₦15.3B — 45% below target under his watch', 'Budget execution in key sectors below 60%'],
    verified: true,
    source: 'Bayelsa State Govt; NigeriaGalleria',
  },
  {
    id: 3,
    name: 'Gentle Emelah',
    position: 'Attorney-General & Commissioner for Justice',
    portfolio: 'Justice',
    icon: '⚖',
    tier: 'commissioner',
    fitScore: 88,
    fitLabel: 'QUALIFIED',
    education: 'LLB, BL — legal practitioner',
    yearsRelevant: 20,
    background: 'Qualified legal practitioner. The AG role requires core legal expertise in Nigerian constitutional and administrative law, criminal justice, and state legal advisory.',
    requiredProfile: 'Must be a qualified barrister and solicitor with deep knowledge of Nigerian law. Serves as chief legal adviser to the state.',
    strengths: ['Legally qualified', 'Relevant professional background', 'No credible reports of incompetence in role'],
    concerns: ['State attempted to block ICPC investigation in 2022 — AG office implicated in that legal action'],
    verified: true,
    source: 'Bayelsa State Govt; NBA records',
  },
  {
    id: 4,
    name: 'Moses Teibowei',
    position: 'Commissioner for Works & Infrastructure',
    portfolio: 'Infrastructure',
    icon: '🏗',
    tier: 'commissioner',
    fitScore: 44,
    fitLabel: 'PARTIAL',
    education: 'Business/management background reported; engineering credentials unconfirmed',
    yearsRelevant: 5,
    background: 'Business and community leadership background. No publicly confirmed engineering or technical qualification. Roads sector is the most critical in Bayelsa — requires technical understanding of construction, procurement, and flood-proofing.',
    requiredProfile: 'Should hold civil/structural engineering qualification or equivalent. Must understand construction specifications, contractor evaluation, flood hydrology, and infrastructure lifecycle costing.',
    strengths: ['Political experience', 'Community connections across LGAs'],
    concerns: ['No confirmed engineering degree or professional membership (NSE, COREN)', 'Roads sector: ₦43.1B unspent in FY2024', 'Yenagoa–Oporoma road 2 years overdue with no resolution', 'Technical oversight gap likely contributing to project delays'],
    verified: false,
    source: 'Bayelsa State Govt [UNVERIFIED — credentials not publicly confirmed]',
  },
  {
    id: 5,
    name: 'Geraldine Banigo',
    position: 'Commissioner for Health',
    portfolio: 'Health',
    icon: '🏥',
    tier: 'commissioner',
    fitScore: 91,
    fitLabel: 'QUALIFIED',
    education: 'MBBS; specialist medical training; public health background',
    yearsRelevant: 25,
    background: 'Medical doctor with specialist training and public health expertise. Previously served as Commissioner for Health in earlier administrations. One of the most credentialed commissioners in the cabinet.',
    requiredProfile: 'Should hold medical degree (MBBS) or strong public health qualification. Oversees hospitals, WASH, maternal health, and primary care for 2.3M people.',
    strengths: ['Medical doctor — directly qualified', 'Long experience in state health system', 'Understands Niger Delta-specific disease burden'],
    concerns: ['Health facilities still at 38% functionality under her watch', 'WASH access at 9% despite her tenure — no breakthrough achieved'],
    verified: true,
    source: 'Bayelsa State Govt; MDCN; Premium Times',
  },
  {
    id: 6,
    name: 'Preye Aganaba',
    position: 'Commissioner for Education',
    portfolio: 'Education',
    icon: '📚',
    tier: 'commissioner',
    fitScore: 58,
    fitLabel: 'PARTIAL',
    education: 'Legal background; no confirmed formal education qualification',
    yearsRelevant: 8,
    background: 'Legal and political background. Education leadership in Nigeria increasingly requires policy and management skills, but deep sector experience (teaching, curriculum, pedagogy) is still valuable for credibility.',
    requiredProfile: 'Ideally holds education degree or senior education management experience. Must oversee UBEC funding, school rehabilitation (1000 Schools plan), teacher deployment, and WAEC performance.',
    strengths: ['Policy and administrative experience', 'Able to navigate federal-state education funding dynamics'],
    concerns: ['1000 Schools plan: only 214 of 500 target completed by deadline', '85,000 children out of school', 'WAEC pass rate at 41% — 11pts below national average', 'No confirmed education sector qualification'],
    verified: false,
    source: 'Bayelsa State Govt [UNVERIFIED — credentials not fully confirmed]',
  },
  {
    id: 7,
    name: 'Iselema Gbaingbaин',
    position: 'Commissioner for Environment',
    portfolio: 'Environment',
    icon: '🌿',
    tier: 'commissioner',
    fitScore: 31,
    fitLabel: 'UNQUALIFIED',
    education: 'Background in business/politics — no environmental science credentials confirmed',
    yearsRelevant: 2,
    background: 'Political appointment. No publicly confirmed environmental science, ecology, or petroleum engineering background. Overseeing a state with 47 active oil spill sites, degraded fisheries, and a pipeline network 73% past its lifespan.',
    requiredProfile: 'Must have environmental science, ecology, petroleum engineering, or environmental law background. Should be able to hold oil companies to account, commission credible EIAs, and lead remediation negotiations.',
    strengths: ['Political connections may help negotiate with oil companies'],
    concerns: ['No confirmed environmental science qualification', '47 active spill sites — zero remediated in tenure', 'No remediation agency established', 'Only ₦1.1B of ₦4.2B budget spent (26%)', '"Zero oil spill sites by 2025" promise made by governor — no progress'],
    verified: false,
    source: 'Bayelsa State Govt [UNVERIFIED — credentials not publicly confirmed]',
  },
  {
    id: 8,
    name: 'Tonye Isenah',
    position: 'Commissioner for Agriculture',
    portfolio: 'Agriculture',
    icon: '🌾',
    tier: 'commissioner',
    fitScore: 52,
    fitLabel: 'PARTIAL',
    education: 'Science background; some agricultural exposure reported',
    yearsRelevant: 6,
    background: 'Some science and agricultural exposure. Bayelsa has significant blue economy potential — fisheries, aquaculture, and riverine farming — that is largely untapped. Role requires both technical and commercial agricultural development skills.',
    requiredProfile: 'Agricultural science, fisheries, agronomy, or agribusiness background. Should be able to develop aquaculture, provide extension services, and unlock the blue economy potential.',
    strengths: ['Some agricultural sector familiarity', 'Understands riverine farming context'],
    concerns: ['Aquaculture potential largely unrealised', 'No major food security programme launched', 'Agriculture budget execution not publicly reported'],
    verified: false,
    source: 'Bayelsa State Govt [UNVERIFIED]',
  },
  {
    id: 9,
    name: 'Ayibatonye Maduku',
    position: 'Commissioner for Information & Orientation',
    portfolio: 'Information',
    icon: '📡',
    tier: 'commissioner',
    fitScore: 65,
    fitLabel: 'PARTIAL',
    education: 'Communications/media background; journalism experience reported',
    yearsRelevant: 10,
    background: 'Communications and media experience. The Information Ministry is crucial for government-citizen transparency, crisis communication (flooding, oil spills), and digital engagement.',
    requiredProfile: 'Communications, journalism, or media management background. Should run proactive government communication — including publishing budget data, project trackers, and crisis updates.',
    strengths: ['Media and communications background', 'Understands press dynamics'],
    concerns: ['Government website and data transparency remain poor', 'No live project tracker or budget dashboard published', 'Reactive rather than proactive communication on failures'],
    verified: false,
    source: 'Bayelsa State Govt [UNVERIFIED]',
  },
  {
    id: 10,
    name: 'David Aketeh',
    position: 'Chief of Staff',
    portfolio: 'Executive Office',
    icon: '🗂',
    tier: 'executive',
    fitScore: 60,
    fitLabel: 'PARTIAL',
    education: 'Political science / public administration background',
    yearsRelevant: 8,
    background: 'Political loyalist and close Diri associate. Chief of Staff role is inherently political but requires strong coordination ability to translate the Governor\'s agenda into deliverable workplans across ministries.',
    requiredProfile: 'Strong project management, political coordination, and governance experience. Must drive cross-ministry accountability, resolve contractor disputes, and hold commissioners to delivery timelines.',
    strengths: ['Governor trust and access', 'Political network', 'Bayelsa institutional knowledge'],
    concerns: ['Power Company dispute unresolved for 2+ years — coordination failure', 'Multiple project overruns suggest weak cross-ministry accountability', 'No evidence of published delivery tracking system'],
    verified: false,
    source: 'Bayelsa State Govt [UNVERIFIED]',
  },
  {
    id: 11,
    name: 'Emmanuel Ekaka',
    position: 'Commissioner for Economic Development',
    portfolio: 'Economy',
    icon: '📊',
    tier: 'commissioner',
    fitScore: 48,
    fitLabel: 'PARTIAL',
    education: 'Business administration background; economics exposure',
    yearsRelevant: 7,
    background: 'Business and administrative background. Economic development in Bayelsa requires a clear strategy for diversification beyond oil — particularly gas monetisation, SME growth, and IGR expansion.',
    requiredProfile: 'Economics, development finance, or business development background. Should be driving IGR growth, gas monetisation strategy, SME ecosystem, and investor attraction.',
    strengths: ['Business network', 'Understanding of private sector dynamics'],
    concerns: ['IGR at ₦15.3B vs ₦28B target under this tenure', 'Youth unemployment at 40.3%', 'SMEs registered: 3,240 vs 10,000 target', 'No published gas monetisation roadmap for 18TCF reserve'],
    verified: false,
    source: 'Bayelsa State Govt [UNVERIFIED]',
  },
  {
    id: 12,
    name: 'Konbowei Benson',
    position: 'Commissioner for Power / Energy',
    portfolio: 'Electricity',
    icon: '⚡',
    tier: 'commissioner',
    fitScore: 38,
    fitLabel: 'UNQUALIFIED',
    education: 'Political/community background; no engineering or energy credentials confirmed',
    yearsRelevant: 3,
    background: 'Primarily a political figure. The electricity portfolio in Bayelsa is among the most technically demanding — involving gas-to-power infrastructure, grid connectivity, NERC regulation, and the stalled 300MW independent power project.',
    requiredProfile: 'Electrical or mechanical engineering background (or energy policy expertise). Must negotiate with NERC, manage GE/Oando contracts, oversee the gas turbine project, and build the Bayelsa Power Company out of its stall.',
    strengths: ['Political mandate to prioritise electricity'],
    concerns: ['No confirmed engineering or energy qualification', 'Bayelsa Power Company (300MW) stalled 2+ years — no resolution on his watch', '60MW gas turbine missed December 2024 deadline', 'Average power: 4.2hrs/day — 74% below target', 'Rural electrification at 12% vs 35% target'],
    verified: false,
    source: 'Bayelsa State Govt [UNVERIFIED — credentials not publicly confirmed]',
  },
]

export const GOVERNOR = {
  name: 'Sen. Douye Diri', title: 'Executive Governor',
  state: 'Bayelsa State', party: 'PDP',
  inauguration: 'February 14, 2020', termEnds: 'February 2028',
  capital: 'Yenagoa', population: '2,278,663', area: '10,773 km²',
  lgas: 8, overallScore: 39, yearsInOffice: 5,
  promisesTracked: 24, promisesKept: 6, promisesPartial: 8, promisesBroken: 10,
}

// ── SECTORS ──────────────────────────────────────────────────────────────────

export const SECTORS = [
  {
    id: 'education', name: 'Education', icon: '📚', score: 51,
    status: 'POOR', severity: 'amber',
    budgetAllocated: 62.4, budgetSpent: 47.8,
    metrics: [
      { label: 'Adult Literacy Rate',    value: '86.83%', target: '95%',   progress: 91 },
      { label: 'Net Enrollment Rate',    value: '72%',    target: '95%',   progress: 76 },
      { label: 'Schools Rehabilitated', value: '214',    target: '500',   progress: 43 },
      { label: 'WAEC Pass Rate',         value: '41%',    target: '65%',   progress: 63 },
    ],
    headline: '86.83%', headlineLabel: 'Adult literacy — 11th highest in Nigeria',
    keyFailure: 'Despite strong literacy, 85,000 children out of school. WAEC pass rate 11 pts below national average.',
    source: 'NBS / Zikoko 2024; UBEC 2023; WAEC 2024',
  },
  {
    id: 'roads', name: 'Roads & Infrastructure', icon: '🛣️', score: 29,
    status: 'CRITICAL', severity: 'red',
    budgetAllocated: 95.2, budgetSpent: 52.1,
    metrics: [
      { label: 'Roads Completed',                value: '147 km', target: '500 km',     progress: 29 },
      { label: 'Riverine Communities Connected', value: '23%',    target: '60%',        progress: 38 },
      { label: 'Major Projects On Schedule',     value: '1 of 6', target: '6 projects', progress: 17 },
    ],
    headline: '₦43.1B', headlineLabel: 'Roads budget unspent in FY2024',
    keyFailure: 'Yenagoa–Oporoma road 60% done — 2 years overdue. Annual flooding destroys roads within 18 months.',
    source: 'BudgIT Bayelsa FY2024',
  },
  {
    id: 'economy', name: 'Economy & Jobs', icon: '📊', score: 35,
    status: 'POOR', severity: 'red',
    budgetAllocated: 35.6, budgetSpent: 18.2,
    metrics: [
      { label: 'Youth Unemployment',   value: '40.3%', target: '≤30%',  progress: 22 },
      { label: 'IGR vs ₦28B Target',  value: '₦15.3B',target: '₦28B',  progress: 55 },
      { label: 'New SMEs Registered', value: '3,240', target: '10,000', progress: 32 },
    ],
    headline: '96.2%', headlineLabel: 'Revenue from oil — not internally generated',
    keyFailure: 'IGR ₦15.3B vs ₦28B target — 45.4% shortfall. Zero economic diversification after 5 years.',
    source: 'NBS Q2 2024; Bayelsa State Revenue Service',
  },
  {
    id: 'flood', name: 'Flood & Disaster', icon: '🌊', score: 18,
    status: 'CRITICAL', severity: 'red',
    budgetAllocated: 8.4, budgetSpent: 6.1,
    metrics: [
      { label: 'Permanent Flood Structures', value: '0',   target: '12',    progress: 0  },
      { label: 'Early Warning Systems',      value: '2',   target: '8 LGAs',progress: 25 },
      { label: 'Displaced Persons Re-housed',value: '14%', target: '100%',  progress: 14 },
    ],
    headline: '1.3M+', headlineLabel: 'People displaced in 2022 floods alone',
    keyFailure: 'No permanent flood infrastructure in 5 years. Two-thirds of Bayelsa floods 3+ months annually.',
    source: 'NEMA 2022; World Bank Nigeria Floods',
  },
  {
    id: 'health', name: 'Health & WASH', icon: '🏥', score: 33,
    status: 'CRITICAL', severity: 'red',
    budgetAllocated: 28.3, budgetSpent: 19.6,
    metrics: [
      { label: 'Basic WASH Access',           value: '9%', target: '60%', progress: 15 },
      { label: 'Health Facilities Functional', value: '38%',target: '80%', progress: 48 },
      { label: 'Skilled Birth Attendance',    value: '52%',target: '85%', progress: 61 },
    ],
    headline: '91%', headlineLabel: 'Residents lack basic water or sanitation',
    keyFailure: 'Only 9% WASH access vs 39% national average. Maternal mortality among Nigeria\'s highest.',
    source: 'UNICEF WASHNORM 2021; NBS MPI 2022',
  },
  {
    id: 'environment', name: 'Environment & Oil Spills', icon: '🌿', score: 12,
    status: 'CRITICAL', severity: 'red',
    budgetAllocated: 4.2, budgetSpent: 1.1,
    metrics: [
      { label: 'Active Oil Spill Sites',      value: '47', target: '0',   progress: 0  },
      { label: 'Remediation Sites Completed', value: '0',  target: '47',  progress: 0  },
      { label: 'Legal Actions vs Oil Cos.',   value: '1',  target: '10+', progress: 10 },
    ],
    headline: '47', headlineLabel: 'Active oil spill sites — zero remediated',
    keyFailure: 'Fishing economy collapsed in 6 LGAs. No Remediation Agency. 73% of pipelines past lifespan.',
    source: 'Amnesty International 2023; NOSDRA',
  },
  {
    id: 'industry', name: 'Industry & Energy', icon: '⚙️', score: 48,
    status: 'POOR', severity: 'amber',
    budgetAllocated: 22.6, budgetSpent: 14.8,
    metrics: [
      { label: 'Share of Nigeria Oil Output', value: '23.4%', target: 'maintain', progress: 78 },
      { label: 'Gas Reserves Monetised',      value: '~8%',   target: '30%',      progress: 27 },
      { label: 'Non-Oil Industry Growth',     value: '3.1%',  target: '12% pa',   progress: 26 },
    ],
    headline: '₦4.63T', headlineLabel: 'State GDP — 11th richest state in Nigeria',
    keyFailure: '18 trillion cubic feet gas reserve — Nigeria\'s largest — largely unmonetised.',
    source: 'NBS GDP Rankings 2024; NNPC 2024',
  },
  {
    id: 'electricity', name: 'Electricity', icon: '⚡', score: 28,
    status: 'CRITICAL', severity: 'red',
    budgetAllocated: 18.5, budgetSpent: 11.2,
    metrics: [
      { label: 'Avg. Daily Power Supply',   value: '4.2 hrs',target: '16 hrs', progress: 26 },
      { label: 'Rural Electrification Rate',value: '12%',    target: '35%',   progress: 34 },
      { label: 'Solar/Renewable Share',     value: '8%',     target: '25%',   progress: 32 },
      { label: 'Projects Completed',        value: '1 of 8', target: '8',     progress: 13 },
    ],
    headline: '4.2 hrs/day', headlineLabel: 'Average power supply — 74% below target',
    keyFailure: 'Bayelsa Power Company (300MW, ₦8B spent) stalled since August 2022. Contractor dispute unresolved 2+ years.',
    source: 'NERC Q3 2024; Bayelsa State Power Authority',
  },
]

// ── PROJECTS ─────────────────────────────────────────────────────────────────

export const PROJECTS = [
  {
    id: 'gas-turbine', name: '60MW Gas Turbine Power Plant',
    location: 'Elebele, Ogbia LGA', sector: 'Electricity', icon: '⚡',
    status: 'ongoing', completion: 99,
    budget: '₦45B', contractor: 'GE Power / Oando Gas',
    startDate: 'Oct 2024', targetDate: 'Dec 2024', revisedDate: 'Q2 2025',
    description: '8 units of 60MW gas turbines installed at Elebele, fed by Oando gas manifold. Governor Diri expressed disappointment at missing the December deadline. President Tinubu expected to inaugurate.',
    source: 'Mangrove Pen; Leadership Newspaper; Bayelsa Govt 2025',
    milestones: [
      { date: 'Oct 2024', label: 'Construction begins at Elebele',     done: true  },
      { date: 'Dec 2024', label: 'Target completion (missed — delay)', done: false },
      { date: 'Mar 2025', label: 'Tinubu inauguration announced',      done: true  },
      { date: 'Q2 2025',  label: 'Grid connection & commissioning',    done: false },
    ],
  },
  {
    id: 'yenagoa-oporoma', name: 'Yenagoa–Oporoma Road',
    location: 'Southern Ijaw LGA', sector: 'Roads', icon: '🛣️',
    status: 'ongoing', completion: 60,
    budget: '₦28B', contractor: 'Dantata & Sawoe',
    startDate: 'Mar 2021', targetDate: 'Mar 2024', revisedDate: 'TBD',
    description: 'Critical road connecting Yenagoa to Oporoma in Southern Ijaw. 2+ years behind schedule. Annual flooding has damaged completed sections twice.',
    source: 'BudgIT; Bayelsa Ministry of Public Works',
    milestones: [
      { date: 'Mar 2021', label: 'Groundbreaking ceremony',       done: true  },
      { date: 'Dec 2022', label: '40% completion reached',        done: true  },
      { date: 'Mar 2024', label: 'Original deadline (missed)',     done: false },
      { date: 'Dec 2024', label: '60% completion',                done: true  },
      { date: 'TBD',      label: 'Full completion',               done: false },
    ],
  },
  {
    id: 'angiama-bridge', name: 'Angiama–Oporoma Bridge',
    location: 'Southern Ijaw LGA', sector: 'Roads', icon: '🌉',
    status: 'ongoing', completion: 85,
    budget: '₦15B', contractor: 'CPCC Construction',
    startDate: 'Jan 2022', targetDate: 'Dec 2023', revisedDate: 'Q1 2025',
    description: 'Bridge connecting isolated Southern Ijaw communities year-round. Near completion — one of the administration\'s most credible infrastructure wins.',
    source: 'Bayelsa State Govt; The Will Nigeria',
    milestones: [
      { date: 'Jan 2022', label: 'Construction begins',           done: true  },
      { date: 'Dec 2023', label: 'Target completion (missed)',     done: false },
      { date: 'Dec 2024', label: '85% completion',                done: true  },
      { date: 'Q1 2025',  label: 'Projected full completion',     done: false },
    ],
  },
  {
    id: 'nembe-brass-road', name: 'Nembe–Brass Senatorial Road',
    location: 'Nembe / Brass LGAs', sector: 'Roads', icon: '🛣️',
    status: 'ongoing', completion: 40,
    budget: '₦32B', contractor: 'CCECC Nigeria',
    startDate: 'Jun 2023', targetDate: 'Jun 2026', revisedDate: 'TBD',
    description: 'One of three senatorial roads. Connects Nembe and Brass — two of the most historically neglected LGAs. Currently 40% complete.',
    source: 'Bayelsa State Govt; Sahara Reporters',
    milestones: [
      { date: 'Jun 2023', label: 'Construction begins',           done: true  },
      { date: 'Dec 2024', label: '40% completion',                done: true  },
      { date: 'Jun 2026', label: 'Target completion',             done: false },
    ],
  },
  {
    id: 'stadium', name: '25,000-Seat International Stadium',
    location: 'Yenagoa', sector: 'Sports', icon: '🏟️',
    status: 'ongoing', completion: 45,
    budget: '₦35B', contractor: 'CGC Nigeria',
    startDate: 'Mar 2022', targetDate: 'Dec 2025', revisedDate: 'TBD',
    description: 'International-standard stadium to host regional and continental sporting events. Will anchor Bayelsa\'s sports tourism ambitions.',
    source: 'Bayelsa State Sports Council',
    milestones: [
      { date: 'Mar 2022', label: 'Groundbreaking',                done: true  },
      { date: 'Dec 2023', label: '30% completion',                done: true  },
      { date: 'Dec 2024', label: '45% completion',                done: true  },
      { date: 'Dec 2025', label: 'Target completion',             done: false },
    ],
  },
  {
    id: 'secretariat', name: '9-Storey State Secretariat',
    location: 'Yenagoa', sector: 'Administration', icon: '🏢',
    status: 'ongoing', completion: 65,
    budget: '₦18B', contractor: 'Julius Berger',
    startDate: 'Sep 2021', targetDate: 'Sep 2023', revisedDate: 'TBD',
    description: 'Modern government complex to centralise civil service. 65% complete and running behind schedule.',
    source: 'Bayelsa State Govt',
    milestones: [
      { date: 'Sep 2021', label: 'Groundbreaking',                done: true  },
      { date: 'Sep 2023', label: 'Target completion (missed)',     done: false },
      { date: 'Dec 2024', label: '65% complete',                  done: true  },
      { date: 'TBD',      label: 'Full completion',               done: false },
    ],
  },
  {
    id: 'bayelsa-power-company', name: 'Bayelsa Power Company (300MW)',
    location: 'Yenagoa', sector: 'Electricity', icon: '⚡',
    status: 'stalled', completion: 35,
    budget: '₦60B (est.)', contractor: 'DISPUTED',
    startDate: 'Nov 2020', targetDate: 'Nov 2025', revisedDate: 'STALLED',
    description: 'Flagship 300MW independent power project. ₦8B consumed. Contractor dispute halted work August 2022. No resolution in 2+ years. Governor has expressed no clear timeline for restart.',
    source: 'NERC; Bayelsa State Power Authority; Punch 2022',
    milestones: [
      { date: 'Nov 2020', label: 'MOU signed — 5-year target',    done: true  },
      { date: 'Jun 2021', label: 'Site preparation begins',       done: true  },
      { date: 'Aug 2022', label: '⚠ STALLED — contractor dispute',done: false },
      { date: 'Dec 2024', label: 'Still unresolved — 2 years on', done: false },
    ],
  },
  {
    id: '1000-schools', name: '"1000 Schools" Emergency Education Plan',
    location: 'All 8 LGAs', sector: 'Education', icon: '📚',
    status: 'stalled', completion: 43,
    budget: '₦22B', contractor: 'Multiple',
    startDate: 'Jan 2022', targetDate: 'Dec 2024', revisedDate: 'Unknown',
    description: 'Promised rehabilitation of 1,000 schools across Bayelsa. Only 214 schools completed as of December 2023 — 57% short of target. No updated timeline published.',
    source: 'UBEC; BudgIT; Bayelsa Govt',
    milestones: [
      { date: 'Jan 2022', label: 'Plan announced publicly',       done: true  },
      { date: 'Jun 2023', label: '150 schools completed',         done: true  },
      { date: 'Dec 2023', label: '214/500 target reached',        done: true  },
      { date: 'Dec 2024', label: 'Final 500 deadline (missed)',   done: false },
    ],
  },
  {
    id: 'glory-drive', name: 'Glory Drive Expansion (Phase 2 & 3)',
    location: 'Yenagoa', sector: 'Roads', icon: '🛣️',
    status: 'completed', completion: 100,
    budget: '₦4.8B', contractor: 'RCC Nigeria',
    startDate: 'Apr 2021', targetDate: 'Dec 2022', revisedDate: 'Mar 2023',
    description: 'Expansion of the main commercial corridor in Yenagoa. Completed March 2023 — slightly behind original target but ultimately delivered. Improved traffic flow and commercial activity.',
    source: 'Bayelsa State Ministry of Public Works',
    milestones: [
      { date: 'Apr 2021', label: 'Construction begins',           done: true },
      { date: 'Dec 2022', label: 'Target slightly missed',        done: true },
      { date: 'Mar 2023', label: '✓ Completed & commissioned',    done: true },
    ],
  },
  {
    id: 'imiringi-turbine', name: 'Imiringi Gas Turbine Refurbishment',
    location: 'Imiringi, Ogbia LGA', sector: 'Electricity', icon: '⚡',
    status: 'completed', completion: 100,
    budget: '₦2.1B', contractor: 'GE Nigeria',
    startDate: 'Jan 2021', targetDate: 'Jun 2021', revisedDate: 'Aug 2021',
    description: 'Refurbishment of existing Imiringi gas turbine to restore partial power generation. Completed August 2021. Added limited capacity to state grid.',
    source: 'Bayelsa State Govt; NERC',
    milestones: [
      { date: 'Jan 2021', label: 'Works begin',                   done: true },
      { date: 'Aug 2021', label: '✓ Completed & commissioned',    done: true },
    ],
  },
  {
    id: 'health-insurance', name: 'Bayelsa Health Insurance Scheme',
    location: 'State-wide', sector: 'Health', icon: '🏥',
    status: 'completed', completion: 100,
    budget: '₦8B', contractor: 'NHIA Scheme',
    startDate: 'Mar 2021', targetDate: 'Dec 2022', revisedDate: 'Feb 2023',
    description: 'State health insurance scheme expanded to cover more Bayelsa residents. Reduces out-of-pocket healthcare costs. One of the administration\'s genuine social welfare wins.',
    source: 'Bayelsa State Govt; NHIA',
    milestones: [
      { date: 'Mar 2021', label: 'Scheme design begins',          done: true },
      { date: 'Jun 2022', label: 'Pilot in 3 LGAs',              done: true },
      { date: 'Feb 2023', label: '✓ State-wide rollout complete', done: true },
    ],
  },
]

// ── REVENUE ──────────────────────────────────────────────────────────────────

export const REVENUE_SOURCES = [
  { name: 'FAAC Statutory Allocation',  value: 180, pct: 47.4, color: '#1B4FC4', description: 'Federal Account Allocation Committee — Bayelsa\'s share of the federation account based on population, land mass, equality of states, and social development factors.' },
  { name: '13% Oil Derivation Fund',    value: 165, pct: 43.4, color: '#C97400', description: 'Constitutional 13% of on-shore oil revenue returned to oil-producing states. Bayelsa is 2nd highest recipient after Delta State. Received ₦320.45B in 2025 (significant YoY jump).' },
  { name: 'IGR (Internally Generated)', value: 15.3,pct: 4.0,  color: '#008751', description: 'Revenue generated within Bayelsa from taxes, fees, levies, and fines. Critically low at 4% of total revenue — dangerously oil-dependent.' },
  { name: 'Federal Grants & Aids',      value: 12,  pct: 3.2,  color: '#6B3FA0', description: 'Grants from federal government ministries, NDDC allocations, and international development partners (World Bank, USAID, UNICEF).' },
  { name: 'Other / Capital Receipts',   value: 7.7, pct: 2.0,  color: '#0D132D', description: 'Loan repayments, asset disposals, miscellaneous receipts.' },
]

export const IGR_BREAKDOWN = [
  { name: 'Personal Income Tax',  value: 6.2, pct: 41, color: '#0D132D' },
  { name: 'Fees & Levies',        value: 3.8, pct: 25, color: '#1B4FC4' },
  { name: 'Mineral/Natural Res.', value: 2.1, pct: 14, color: '#C97400' },
  { name: 'Fines & Penalties',    value: 1.4, pct: 9,  color: '#008751' },
  { name: 'Land Use Charge',      value: 1.1, pct: 7,  color: '#6B3FA0' },
  { name: 'Others',               value: 0.7, pct: 4,  color: '#7A8799' },
]

export const REVENUE_TREND = [
  { year: '2020', faac: 148, derivation: 62,  igr: 9.1,  total: 225 },
  { year: '2021', faac: 158, derivation: 78,  igr: 10.4, total: 254 },
  { year: '2022', faac: 162, derivation: 112, igr: 11.8, total: 294 },
  { year: '2023', faac: 170, derivation: 140, igr: 13.2, total: 332 },
  { year: '2024', faac: 180, derivation: 165, igr: 15.3, total: 380 },
]

export const IGR_POTENTIAL = [
  { source: 'Digital Tax Collection (Lagos model)',  currentMonthly: 1.3, potentialMonthly: 5.2, gap: 3.9 },
  { source: 'Property & Land Use Tax',               currentMonthly: 0.09, potentialMonthly: 1.5, gap: 1.41 },
  { source: 'Tourism & Hospitality Levies',          currentMonthly: 0.08, potentialMonthly: 0.8, gap: 0.72 },
  { source: 'Fisheries & Aquaculture Licensing',     currentMonthly: 0.05, potentialMonthly: 0.6, gap: 0.55 },
  { source: 'Gas Royalties & Domestic Monetisation', currentMonthly: 0.15, potentialMonthly: 2.1, gap: 1.95 },
]

export const EXPENDITURE_BREAKDOWN = [
  { name: 'Recurrent (Salaries & Admin)', value: 228, pct: 60 },
  { name: 'Capital (Infrastructure)',     value: 114, pct: 30 },
  { name: 'Debt Servicing',               value: 28,  pct: 7  },
  { name: 'Social Transfers',             value: 10,  pct: 3  },
]

// ── OIL MONEY ────────────────────────────────────────────────────────────────

export const OIL_REVENUE_FLOW = [
  { stage: 'Oil extracted from Bayelsa land', value: 100, label: '~$6–8B/yr est.', note: 'Bayelsa produces 23.4% of Nigeria\'s 2.2M bpd' },
  { stage: 'NNPC Opex & Joint Venture costs', value: 82,  label: '~18% deducted', note: 'Operating costs deducted before federation account' },
  { stage: 'Enters Federation Account',        value: 74,  label: '74% of gross',  note: 'FAAC distributes from here' },
  { stage: 'Federal Govt takes (52.68%)',      value: 39,  label: '52.68%',         note: 'Largest single share — federal programmes, Abuja overhead' },
  { stage: 'All 36 States share (26.72%)',     value: 20,  label: '26.72%',         note: 'Bayelsa gets ~1.8% of this (based on formula)' },
  { stage: 'All 774 LGAs share (20.60%)',      value: 15,  label: '20.60%',         note: 'Bayelsa\'s 8 LGAs get a fraction' },
  { stage: '13% Derivation to oil states',     value: 10,  label: '~13%',           note: 'Bayelsa gets ~25% of this pool' },
  { stage: 'Total returning to Bayelsa State', value: 8,   label: '~8% of gross',   note: 'Only ~8 cents of every ₦1 extracted returns to Bayelsa' },
]

export const NNPC_BOARD = [
  { name: 'Bashir Bayo Ojulari', role: 'Group CEO', zone: 'South-West', state: 'Ondo', ethnic: 'Yoruba', type: 'executive' },
  { name: 'Ahmadu Musa Kida',    role: 'Non-Exec. Chairman', zone: 'North-East', state: 'Adamawa', ethnic: 'Fulani', type: 'non-exec' },
  { name: 'Bello Rabiu',         role: 'Non-Exec. Director', zone: 'North-West', state: 'Kano', ethnic: 'Hausa', type: 'non-exec' },
  { name: 'Yusuf Usman',         role: 'Non-Exec. Director', zone: 'North-East', state: 'Borno', ethnic: 'Kanuri', type: 'non-exec' },
  { name: 'Babs Omotowa',        role: 'Non-Exec. Director', zone: 'North-Central', state: 'Kwara', ethnic: 'N/A', type: 'non-exec' },
  { name: 'Austin Avuru',        role: 'Non-Exec. Director', zone: 'South-South', state: 'Rivers', ethnic: 'Ijaw (Kalabari)', type: 'non-exec', note: 'Only South-South rep — covers 6 states, 90% of Nigeria\'s oil' },
  { name: 'David Ige',           role: 'Non-Exec. Director', zone: 'South-West', state: 'Lagos', ethnic: 'Yoruba', type: 'non-exec' },
  { name: 'Henry Obih',          role: 'Non-Exec. Director', zone: 'South-East', state: 'Imo', ethnic: 'Igbo', type: 'non-exec' },
  { name: 'Lydia Shehu Jafiya',  role: 'Perm. Sec., Finance', zone: 'North', state: 'Taraba', ethnic: 'N/A', type: 'ministry' },
  { name: 'Aminu Said Ahmed',    role: 'Ministry of Petroleum Rep.', zone: 'North', state: 'N/A', ethnic: 'N/A', type: 'ministry' },
]

export const OIL_COMPANIES = [
  {
    name: 'SPDC (Shell)', fullName: 'Shell Petroleum Development Company',
    ownership: [
      { entity: 'NNPC',  pct: 55, color: '#0D132D' },
      { entity: 'Shell', pct: 30, color: '#D4A000' },
      { entity: 'Total', pct: 10, color: '#E63946' },
      { entity: 'Agip',  pct: 5,  color: '#008751' },
    ],
    nigeriaPct: '~38% of Bayelsa production',
    annualRevEstimate: '$3–4B from Bayelsa assets',
    communitySpend: '~$36M (1997 figure — not updated)',
    keyIssue: 'SPDC responsible for the majority of Bayelsa\'s 47 active oil spill sites. Claimed sale of onshore assets to Renaisance in 2024 — communities fear abandonment without remediation.',
  },
  {
    name: 'NAOC (Agip)', fullName: 'Nigerian Agip Oil Company (Eni)',
    ownership: [
      { entity: 'NNPC',  pct: 60, color: '#0D132D' },
      { entity: 'Agip',  pct: 20, color: '#008751' },
      { entity: 'ConocoPhillips', pct: 20, color: '#1B4FC4' },
    ],
    nigeriaPct: '~25% of Bayelsa production',
    annualRevEstimate: '$1.5–2B from Bayelsa assets',
    communitySpend: 'Not publicly disclosed',
    keyIssue: 'Responsible for multiple spills in Nembe and Ogbia LGAs. NOSDRA has documented several unreported spills. JV partner with NNPC means government directly profits while communities suffer.',
  },
]

// ── CORRUPTION ───────────────────────────────────────────────────────────────

export const CORRUPTION_CASES = [
  {
    id: 1, governor: 'Diepreye Alamieyeseigha', term: '1999–2005',
    amount: '$55M+ embezzled / £1M cash seized', status: 'convicted',
    severity: 'red', agency: 'EFCC + London Metropolitan Police',
    charge: 'Money laundering, embezzlement of public funds',
    outcome: 'Pleaded guilty 2007. Assets seized. Controversially pardoned by President Jonathan in 2013.',
    detail: 'British police found £1M in cash at his London home in 2005. EFCC charged him with embezzling ~$55M in public funds and approving ₦1.7B in dubious contracts to eight fictitious companies.',
    source: 'HRW; EFCC; BBC; Amnesty International',
  },
  {
    id: 2, governor: 'Timipre Sylva', term: '2008–2012',
    amount: '₦6.46B alleged', status: 'prosecution',
    severity: 'amber', agency: 'EFCC',
    charge: 'Alleged misappropriation of state funds',
    outcome: '48+ properties seized by EFCC. Case ongoing as of last reports. Sylva went on to become Federal Minister of State for Petroleum (2019–2023).',
    detail: 'EFCC is prosecuting former Governor Sylva for alleged misappropriation of ₦6.46 billion in Bayelsa State funds during his tenure.',
    source: 'EFCC; Vanguard; Premium Times',
  },
  {
    id: 3, governor: 'Henry Seriake Dickson (aide)', term: '2012–2020',
    amount: '₦864M', status: 'prosecution',
    severity: 'amber', agency: 'EFCC Port Harcourt Zone',
    charge: 'Procurement fraud via shell company',
    outcome: 'Former SSA Embelekpo Apere arraigned on 10 counts before Federal High Court Yenagoa. Case pending.',
    detail: 'Former SSA on MDGs to Gov. Dickson charged alongside three others with ₦864M procurement fraud through shell company Oriazy Global Link Limited.',
    source: 'EFCC; Premium Times 2021',
  },
  {
    id: 4, governor: 'Douye Diri administration', term: '2020–present',
    amount: 'Undisclosed — under investigation', status: 'investigation',
    severity: 'amber', agency: 'ICPC',
    charge: 'Alleged corrupt practices by state public functionaries',
    outcome: 'Bayelsa State govt went to Federal High Court in 2022 to BLOCK ICPC from accessing financial records. Court dismissed the challenge — ICPC investigation continues.',
    detail: 'ICPC is investigating corruption allegations against current and former public functionaries in Bayelsa. Critically, the Diri administration attempted to legally obstruct ICPC access to government financial records in 2022 — the court sided with ICPC. The attempted obstruction itself raises serious accountability concerns.',
    source: 'ICPC; Premium Times April 2022; PRNigeria',
  },
  {
    id: 5, governor: 'All administrations (systemic)', term: 'Ongoing',
    amount: '₦45B+ unspent FY2024 alone', status: 'systemic',
    severity: 'red', agency: 'BudgIT / Civil Society',
    charge: 'Budget execution failure — possible misappropriation',
    outcome: 'No public accountability mechanism for unspent budgets exists. Funds allocated to roads, electricity, and environment consistently go "missing" from execution.',
    detail: '₦45B+ was allocated in FY2024 but never reached the projects it was budgeted for. Under Nigerian fiscal law, unspent capital allocations that are not returned to the Consolidated Revenue Fund must be accounted for. No public explanation has been provided for the Roads sector\'s ₦43.1B execution gap.',
    source: 'BudgIT FY2024 Budget Implementation Report; IPSAS Nigeria',
  },
  {
    id: 6, governor: 'NDDC (Niger Delta Dev. Commission)', term: '2000–present',
    amount: '₦1.5T+ unaccounted (national)', status: 'investigation',
    severity: 'red', agency: 'National Assembly; EFCC; Forensic Audit',
    charge: 'Systemic fraud and non-execution of Niger Delta projects',
    outcome: 'Forensic audit ordered by Buhari in 2019 uncovered staggering fraud. NDDC meant to develop Bayelsa but has largely failed. Projects ghost-billed for decades.',
    detail: 'The NDDC was created specifically to develop the Niger Delta, including Bayelsa. A 2019 forensic audit found over ₦1.5T in unaccounted expenditure nationwide. Bayelsa communities meant to benefit from NDDC roads, waterways, and electricity projects have seen little delivery.',
    source: 'National Assembly NDDC Probe 2020; Sahara Reporters; Vanguard',
  },
]

// ── RESEARCH PAPERS ──────────────────────────────────────────────────────────

export const RESEARCH_PAPERS = [
  {
    id: 1, year: 2006, type: 'Government Commission Report',
    title: 'An Environmental Genocide: Report of the Bayelsa State Oil and Environmental Commission',
    authors: 'Bayelsa State Oil and Environmental Commission',
    url: 'https://report.bayelsacommission.org/',
    summary: 'Comprehensive government commission documenting the environmental devastation caused by oil companies in Bayelsa. Covers health impacts, economic losses to fishing communities, and the systematic failure of the Nigerian state to protect its citizens from oil exploitation.',
    keyFinding: '47+ active spill sites. Bayelsa communities receive less than 1% of the economic value extracted from their land.',
    tags: ['Environment', 'Oil', 'Human Rights', 'Government'],
    relevance: 'critical',
  },
  {
    id: 2, year: 2019, type: 'Academic Thesis',
    title: 'Corruption in Oil Revenue Distribution and Conflict in Bayelsa State, Nigeria',
    authors: 'Kennesaw State University — International Conflict Management',
    url: 'https://digitalcommons.kennesaw.edu/incmdoc_etd/1/',
    summary: 'Academic study examining how corruption in the oil revenue distribution system — at both federal and state levels — directly fuels armed conflict and community unrest in Bayelsa. Examines the FAAC formula, derivation fund, and how misappropriation compounds resource injustice.',
    keyFinding: 'Corruption in revenue distribution is a primary driver of armed conflict in Bayelsa. The 13% derivation fund does not reach communities.',
    tags: ['Corruption', 'Revenue', 'Conflict', 'Governance'],
    relevance: 'critical',
  },
  {
    id: 3, year: 2022, type: 'Peer-Reviewed Journal Article',
    title: 'Oil Pollution and Conflicts in the Niger Delta: A Study of SPDC in Bayelsa and Rivers State',
    authors: 'ResearchGate (peer reviewed)',
    url: 'https://www.researchgate.net/publication/359932196',
    summary: 'Examines how Shell Petroleum Development Company operations in Bayelsa and Rivers States have caused systematic environmental degradation and triggered community conflicts through oil spills, gas flaring, and hazardous waste discharge.',
    keyFinding: 'SPDC is the primary driver of environmental conflicts in Bayelsa. Communities receive no meaningful compensation relative to extraction value.',
    tags: ['Oil Spills', 'Shell', 'Environment', 'Conflict'],
    relevance: 'high',
  },
  {
    id: 4, year: 2023, type: 'Peer-Reviewed Journal Article',
    title: 'Maladaptation to Environmental Pollution: The Livelihood Dysfunction Trap in Nigeria\'s Niger Delta',
    authors: 'Cambridge Core — Africa Journal',
    url: 'https://www.cambridge.org/core/journals/africa/article/maladaptation-to-environmental-pollution',
    summary: 'Examines how Niger Delta communities — including in Bayelsa — have been forced to adapt to oil pollution rather than remediate it, creating a "livelihood dysfunction trap" where communities normalise devastation.',
    keyFinding: 'State inaction on oil spills forces communities into maladaptive coping strategies that permanently entrench poverty.',
    tags: ['Environment', 'Poverty', 'Livelihoods', 'Fisheries'],
    relevance: 'high',
  },
  {
    id: 5, year: 2025, type: 'Peer-Reviewed Journal Article',
    title: 'Socio-Economic and One-Health Impacts of Pollution-Induced Land Dispossession in the Niger Delta',
    authors: 'ScienceDirect — One Health journal',
    url: 'https://www.sciencedirect.com/science/article/pii/S2949823625001400',
    summary: 'The most recent study (2025) documenting ongoing oil spill devastation in the Niger Delta, covering Bayelsa specifically. Documents extensive degradation of aquatic ecosystems, collapse of fisheries-based livelihoods, and direct health impacts from contamination.',
    keyFinding: 'Oil pollution in Bayelsa is functionally equivalent to forced displacement. Fishing communities face an existential threat with no government response.',
    tags: ['Health', 'Environment', 'Land Rights', '2025'],
    relevance: 'critical',
  },
  {
    id: 6, year: 2025, type: 'Peer-Reviewed Journal Article',
    title: 'The Framing of the Informal Oil Economy in Nigeria: Toward Epistemic Justice',
    authors: 'Nature — Humanities and Social Sciences Communications',
    url: 'https://www.nature.com/articles/s41599-025-05718-7',
    summary: 'Examines how government neglect of Niger Delta communities has driven the rise of artisanal and illegal oil refining as a survival strategy. Argues for a justice-based lens rather than pure criminalisation.',
    keyFinding: 'Artisanal oil refining in Bayelsa is a direct consequence of government neglect and the failure of oil wealth to reach communities.',
    tags: ['Informal Economy', 'Youth', 'Justice', '2025'],
    relevance: 'medium',
  },
  {
    id: 7, year: 2021, type: 'Academic Paper',
    title: 'Insecurity in Bayelsa State: The Issues, Actors and Solutions',
    authors: 'Academia.edu',
    url: 'https://www.academia.edu/62070191/Insecurity_in_Bayelsa_State_The_Issues_Actors_and_Solutions',
    summary: 'Comprehensive analysis of security challenges in Bayelsa — linking oil pollution, political marginalisation, and youth unemployment to armed conflict. Identifies state failure to address root causes as the core problem.',
    keyFinding: 'Environmental degradation and political marginalisation are the root causes of Bayelsa\'s security challenges — not inherent community violence.',
    tags: ['Security', 'Governance', 'Youth', 'Marginalisation'],
    relevance: 'high',
  },
]

// ── TIMELINE ─────────────────────────────────────────────────────────────────

export const TIMELINE = [
  { date: 'Feb 2020', label: 'Gov. Diri inaugurated — first term begins', type: 'milestone' },
  { date: 'Jun 2020', label: '₦500M flood relief fund promised for 2020 victims', type: 'promise' },
  { date: 'Nov 2020', label: 'Bayelsa Power Company MOU signed — 300MW, 5-year target', type: 'promise' },
  { date: 'Mar 2021', label: 'Yenagoa–Oporoma Road begins (3-year deadline given)', type: 'milestone' },
  { date: 'Oct 2021', label: 'Flood relief funds not fully disbursed — legislative inquiry opened', type: 'failure' },
  { date: 'Jan 2022', label: '"1000 Schools" Emergency Education Plan announced', type: 'promise' },
  { date: 'Apr 2022', label: 'Diri govt goes to court to block ICPC investigation — court rules against state', type: 'failure' },
  { date: 'Aug 2022', label: 'Bayelsa Power Company stalled — contractor dispute unresolved', type: 'failure' },
  { date: 'Oct 2022', label: 'Worst flooding in a decade — 1.3M+ residents displaced', type: 'event' },
  { date: 'Feb 2023', label: 'Re-elected for second term (2023–2028)', type: 'milestone' },
  { date: 'Jun 2023', label: 'New IGR target of ₦28B by 2025 announced publicly', type: 'promise' },
  { date: 'Sep 2023', label: 'Promise: "Zero active oil spill sites by 2025" at press conference', type: 'promise' },
  { date: 'Dec 2023', label: 'Only 214 of 500 targeted schools rehabilitated — 57% short', type: 'failure' },
  { date: 'Mar 2024', label: 'Yenagoa–Oporoma Road: 60% complete, 2 years behind schedule', type: 'failure' },
  { date: 'Sep 2024', label: 'IGR ₦15.3B — 45% below ₦28B target with 4 months remaining', type: 'failure' },
  { date: 'Oct 2024', label: '60MW gas turbine construction begins at Elebele', type: 'milestone' },
  { date: 'Dec 2024', label: 'Gas turbine misses December deadline — Diri expresses disappointment', type: 'failure' },
  { date: 'Mar 2025', label: 'Tinubu inauguration of gas turbine announced', type: 'milestone' },
]

// ── BRIGHT SPOTS ─────────────────────────────────────────────────────────────

export const BRIGHT_SPOTS = [
  { icon: '🏆', label: 'NWFL Champions 2024/25',     detail: 'Bayelsa Queens FC — 6th national title, CAF Women\'s Champions League qualification', color: '#008751' },
  { icon: '🥇', label: 'NSF 2025 Medals Table #1',   detail: 'Team Bayelsa topped the National Sports Festival medals table 2025',                  color: '#008751' },
  { icon: '🏖️', label: 'Brass Beach — W. Africa class',detail: 'One of the longest sand beaches in West Africa. Eco-tourism potential unrealised.',   color: '#1B4FC4' },
  { icon: '⛽', label: '23.4% of Nigeria\'s Oil',    detail: 'Bayelsa produces nearly a quarter of Nigeria\'s total oil output — foundational wealth', color: '#C97400' },
  { icon: '🔥', label: '18 TCF Gas Reserve',          detail: 'Nigeria\'s largest gas reservoir — largely unmonetised but a massive asset',           color: '#C97400' },
  { icon: '📖', label: '86.83% Literacy Rate',         detail: '11th highest in Nigeria — above the national average',                                 color: '#0D132D' },
]

// ── SECTOR DETAIL DATA ───────────────────────────────────────────────────────

export const SECTOR_DETAILS = {

  education: {
    overview: 'Bayelsa has Nigeria\'s 11th highest adult literacy rate at 86.83% — a genuine strength. But headline literacy masks deep structural failures: 85,000 children out of school, a WAEC pass rate 11 points below the national average, and a school rehabilitation programme that delivered less than half its target.',
    nationComparison: { label: 'National WAEC avg', national: 52, bayelsa: 41, unit: '%' },
    lgaData: [
      { lga: 'Yenagoa',        enrolled: 78, outOfSchool: 14000, schoolsRehabbed: 48, washFacilities: 61 },
      { lga: 'Ogbia',          enrolled: 71, outOfSchool: 9200,  schoolsRehabbed: 22, washFacilities: 38 },
      { lga: 'Brass',          enrolled: 62, outOfSchool: 12500, schoolsRehabbed: 18, washFacilities: 22 },
      { lga: 'Nembe',          enrolled: 58, outOfSchool: 11000, schoolsRehabbed: 14, washFacilities: 19 },
      { lga: 'Southern Ijaw',  enrolled: 51, outOfSchool: 16800, schoolsRehabbed: 9,  washFacilities: 12 },
      { lga: 'Kolokuma/Opokuma',enrolled: 67, outOfSchool: 7400, schoolsRehabbed: 16, washFacilities: 31 },
      { lga: 'Ekeremor',       enrolled: 54, outOfSchool: 8900,  schoolsRehabbed: 12, washFacilities: 18 },
      { lga: 'Sagbama',        enrolled: 69, outOfSchool: 6200,  schoolsRehabbed: 19, washFacilities: 28 },
    ],
    programs: [
      { name: '1000 Schools Emergency Plan', status: 'stalled', budget: '₦22B', progress: 43, detail: 'Only 214 of targeted 500 schools completed by December 2024 deadline. No revised timeline published.' },
      { name: 'Technical Colleges (All 8 LGAs)', status: 'ongoing', budget: '₦6.4B', progress: 60, detail: 'Vocational colleges under construction in every LGA. Skills-first education approach targeting youth unemployment.' },
      { name: 'UBEC Matching Fund Uptake', status: 'partial', budget: '₦4.1B available', progress: 55, detail: 'Bayelsa frequently fails to provide matching counterpart funds, leaving UBEC money unaccessed.' },
      { name: 'School Feeding Programme', status: 'ongoing', budget: '₦2.8B', progress: 70, detail: 'Federal-funded programme covering primary schools in 5 of 8 LGAs. Irregular — supply chain issues reported.' },
    ],
    keyInstitutions: [
      { name: 'Niger Delta University (NDU)', location: 'Wilberforce Island, Amassoma', type: 'University', students: '~18,000', note: 'State university — underfunded, staff strikes are frequent.' },
      { name: 'University of Africa, Toru-Orua', location: 'Sagbama LGA', type: 'University', students: '~5,000', note: 'Federal university, established 2016. Growing but still building infrastructure.' },
      { name: 'Bayelsa Medical University', location: 'Yenagoa', type: 'Medical University', students: '~800', note: 'Newest state university focused on health sciences. Promising but very early stage.' },
      { name: 'Government Technical College', location: 'Multiple LGAs', type: 'Technical', students: 'Varies', note: 'Underequipped — many lack functional workshops or tools.' },
    ],
    trend: [
      { year: '2020', waec: 38, enrollment: 68, schools: 0 },
      { year: '2021', waec: 39, enrollment: 69, schools: 60 },
      { year: '2022', waec: 40, enrollment: 71, schools: 130 },
      { year: '2023', waec: 41, enrollment: 72, schools: 214 },
      { year: '2024', waec: 41, enrollment: 72, schools: 214 },
    ],
    benchmarks: [
      { state: 'Lagos',   waec: 68, literacy: 97 },
      { state: 'Bayelsa', waec: 41, literacy: 87 },
      { state: 'Rivers',  waec: 55, literacy: 88 },
      { state: 'Delta',   waec: 58, literacy: 89 },
      { state: 'Nat. Avg',waec: 52, literacy: 78 },
    ],
  },

  roads: {
    overview: 'Roads are Bayelsa\'s most visible failure. The state\'s unique geography — mostly creeks, rivers, and wetlands — makes road construction extraordinarily expensive and flood-vulnerable. Of 6 major projects, only 1 is on schedule. ₦43.1B was allocated for roads in FY2024 but never reached communities. Newly built roads are routinely destroyed by annual flooding within 18 months — a structural problem no administration has addressed.',
    nationComparison: { label: 'Projects on schedule vs target', national: 65, bayelsa: 17, unit: '%' },
    lgaData: [
      { lga: 'Yenagoa',         roadsKm: 38, condition: 62, riverineAccess: 71, majorProjects: 3 },
      { lga: 'Ogbia',           roadsKm: 22, condition: 45, riverineAccess: 38, majorProjects: 1 },
      { lga: 'Brass',           roadsKm: 8,  condition: 31, riverineAccess: 18, majorProjects: 1 },
      { lga: 'Nembe',           roadsKm: 6,  condition: 28, riverineAccess: 12, majorProjects: 1 },
      { lga: 'Southern Ijaw',   roadsKm: 4,  condition: 22, riverineAccess: 9,  majorProjects: 1 },
      { lga: 'Kolokuma/Opokuma',roadsKm: 14, condition: 41, riverineAccess: 44, majorProjects: 0 },
      { lga: 'Ekeremor',        roadsKm: 9,  condition: 35, riverineAccess: 21, majorProjects: 0 },
      { lga: 'Sagbama',         roadsKm: 18, condition: 48, riverineAccess: 51, majorProjects: 0 },
    ],
    programs: [
      { name: 'Yenagoa–Oporoma Road', status: 'stalled', budget: '₦28B', progress: 60, detail: '2 years behind schedule. Annual flooding has damaged completed sections twice. Contractor (Dantata & Sawoe) under pressure.' },
      { name: 'Angiama–Oporoma Bridge', status: 'ongoing', budget: '₦15B', progress: 85, detail: 'One of the admin\'s most credible wins — near completion. Will connect isolated Southern Ijaw communities.' },
      { name: 'Nembe–Brass Senatorial Road', status: 'ongoing', budget: '₦32B', progress: 40, detail: 'Connects two most neglected LGAs. Currently 40% done with 2 years remaining on revised deadline.' },
      { name: 'Glory Drive Phase 2 & 3', status: 'completed', budget: '₦4.8B', progress: 100, detail: 'Main commercial corridor in Yenagoa. Completed March 2023. Improved traffic and trade.' },
      { name: 'Sagbama–Ekeremor Road', status: 'ongoing', budget: '₦19B', progress: 30, detail: 'Critical senatorial road. Slow progress — flooding concerns delaying earthworks.' },
      { name: 'East-West Coastal Road (Federal)', status: 'stalled', budget: 'Federal — undisclosed', progress: 15, detail: 'Federal government project through Bayelsa. Largely stalled. NDDC involvement with known fraud history.' },
    ],
    keyFacts: [
      'Only 147km of the 500km road target completed in 5 years',
      'Bayelsa has only ~119km of paved roads — vs Lagos\'s 9,000km+',
      'Riverine communities rely on boats — 35% of the state is accessible by water only',
      'Average road project cost in Bayelsa is 40–60% higher than national average due to swamp terrain',
      'Annual flood damage to roads estimated at ₦8–12B — erasing most capital investment',
      'No flood-proofing clause in any current road contract reviewed by BudgIT',
    ],
    trend: [
      { year: '2020', completed: 0, budget: 62, spent: 38 },
      { year: '2021', completed: 28, budget: 74, spent: 41 },
      { year: '2022', completed: 67, budget: 88, spent: 47 },
      { year: '2023', completed: 118, budget: 91, spent: 49 },
      { year: '2024', completed: 147, budget: 95, spent: 52 },
    ],
  },

  economy: {
    overview: 'Bayelsa has a ₦4.63 trillion GDP — making it Nigeria\'s 11th richest state per capita. Yet 40.3% of youth are unemployed and IGR is ₦15.3B against a ₦28B target. The paradox: massive oil wealth flows through the state but does not translate to jobs, enterprise, or diversification. After 5 years, there is no published economic diversification strategy.',
    nationComparison: { label: 'Youth unemployment vs national avg', national: 33, bayelsa: 40, unit: '%' },
    lgaData: [
      { lga: 'Yenagoa',         youthUnemployment: 32, smes: 1840, avgIncome: 68000, mainActivity: 'Civil service, trade' },
      { lga: 'Ogbia',           youthUnemployment: 41, smes: 280,  avgIncome: 42000, mainActivity: 'Oil communities, fishing' },
      { lga: 'Brass',           youthUnemployment: 48, smes: 140,  avgIncome: 31000, mainActivity: 'Fishing, artisanal refining' },
      { lga: 'Nembe',           youthUnemployment: 52, smes: 110,  avgIncome: 28000, mainActivity: 'Fishing, informal trade' },
      { lga: 'Southern Ijaw',   youthUnemployment: 55, smes: 80,   avgIncome: 24000, mainActivity: 'Fishing, farming' },
      { lga: 'Kolokuma/Opokuma',youthUnemployment: 38, smes: 190,  avgIncome: 36000, mainActivity: 'Farming, fishing' },
      { lga: 'Ekeremor',        youthUnemployment: 44, smes: 160,  avgIncome: 33000, mainActivity: 'Fishing, farming' },
      { lga: 'Sagbama',         youthUnemployment: 36, smes: 440,  avgIncome: 41000, mainActivity: 'Farming, trade' },
    ],
    programs: [
      { name: 'Bayelsa State Microfinance Bank', status: 'ongoing', budget: '₦5B capitalisation', progress: 55, detail: 'State microfinance bank targeting SME loans. Disbursement rate low — bureaucratic barriers reported.' },
      { name: 'BYSA (Youth Empowerment)', status: 'partial', budget: '₦3.2B', progress: 40, detail: 'Youth empowerment programme. Training provided but job placement rate unknown — no published outcome data.' },
      { name: 'Bayelsa Palm (Oil Palm)', status: 'ongoing', budget: '₦8.1B', progress: 35, detail: 'Palm oil development initiative to tap agricultural diversification. Slow — land tenure disputes complicating expansion.' },
      { name: 'Yenagoa Industrial Layout', status: 'stalled', budget: '₦4.4B', progress: 20, detail: 'Industrial estate to host manufacturing SMEs. Largely undeveloped after years of announcement.' },
    ],
    keyFacts: [
      'State GDP: ₦4.63T — 11th in Nigeria despite being one of the smallest states by land',
      '96.2% of revenue from oil — among the most oil-dependent states in Nigeria',
      'IGR per capita: ~₦6,700/year — vs Lagos at ~₦49,000/year',
      'No major manufacturing employer in the state — all large employers are government or oil sector',
      'Tourism receipts estimated at <₦500M annually — well below the potential given beaches and eco-tourism',
      '18 trillion cubic feet of gas — Nigeria\'s largest reserve — contributes <8% to state revenues',
      'Bayelsa has no functioning industrial estate or special economic zone',
    ],
    trend: [
      { year: '2020', igr: 9.1, unemployment: 42, smes: 1800, gdp: 3.8 },
      { year: '2021', igr: 10.4, unemployment: 41, smes: 2100, gdp: 4.1 },
      { year: '2022', igr: 11.8, unemployment: 41, smes: 2500, gdp: 4.3 },
      { year: '2023', igr: 13.2, unemployment: 40, smes: 2900, gdp: 4.5 },
      { year: '2024', igr: 15.3, unemployment: 40, smes: 3240, gdp: 4.63 },
    ],
  },

  flood: {
    overview: 'Flooding is Bayelsa\'s most catastrophic and most preventable crisis. Two-thirds of the state floods annually for 3+ months. The 2022 floods — the worst in a decade — displaced 1.3 million people and destroyed an estimated ₦180B in property and infrastructure. Five years into the Diri administration, not a single permanent flood control structure has been commissioned.',
    nationComparison: { label: 'Population flood-affected annually', national: 8, bayelsa: 67, unit: '%' },
    lgaData: [
      { lga: 'Yenagoa',         floodMonths: 2, displaced2022: 180000, earlyWarning: true,  damageNbn: 18 },
      { lga: 'Ogbia',           floodMonths: 4, displaced2022: 142000, earlyWarning: false, damageNbn: 24 },
      { lga: 'Brass',           floodMonths: 5, displaced2022: 198000, earlyWarning: false, damageNbn: 31 },
      { lga: 'Nembe',           floodMonths: 5, displaced2022: 162000, earlyWarning: false, damageNbn: 28 },
      { lga: 'Southern Ijaw',   floodMonths: 6, displaced2022: 241000, earlyWarning: false, damageNbn: 38 },
      { lga: 'Kolokuma/Opokuma',floodMonths: 3, displaced2022: 98000,  earlyWarning: true,  damageNbn: 14 },
      { lga: 'Ekeremor',        floodMonths: 4, displaced2022: 156000, earlyWarning: false, damageNbn: 21 },
      { lga: 'Sagbama',         floodMonths: 3, displaced2022: 123000, earlyWarning: false, damageNbn: 16 },
    ],
    programs: [
      { name: 'Flood Early Warning System', status: 'partial', budget: '₦1.2B', progress: 25, detail: 'Only 2 of 8 LGAs have functional early warning systems. NIHSA partnership not fully implemented.' },
      { name: 'Yenagoa Drainage Masterplan', status: 'stalled', budget: '₦6.8B', progress: 10, detail: 'Announced 2021. Earthworks have not commenced in most target areas. No completion date set.' },
      { name: 'IDP Camp Infrastructure', status: 'partial', budget: '₦2.1B', progress: 40, detail: 'Internally displaced persons camps upgraded in Yenagoa. Riverine LGA camps remain inadequate.' },
      { name: 'Flood-Resistant Road Design', status: 'not started', budget: 'Not budgeted', progress: 0, detail: 'No flood-proofing standard has been mandated in road contracts. Roads are destroyed by each flood season.' },
    ],
    keyFacts: [
      '2022 floods: worst in a decade — 1.3M+ displaced across all 8 LGAs',
      'Bayelsa sits at mean sea level — 5mm of sea level rise removes significant land area permanently',
      'Annual flood damage estimated at ₦30–50B — exceeding the state\'s entire roads budget',
      'Only 2 of 8 LGAs have functioning early warning systems',
      'Zero permanent flood embankments or retention infrastructure commissioned in 5 years',
      'NEMA consistently rates Bayelsa highest-risk for flooding nationally',
      'Climate projections show 30–40% increase in extreme flood events in South-South by 2040',
      '14% of displaced persons from 2022 floods have been formally re-housed',
    ],
    floodHistory: [
      { year: '2020', displaced: 410000, damageNbn: 28, govtResponse: 'Emergency relief — ₦500M fund promised, not fully disbursed' },
      { year: '2021', displaced: 320000, damageNbn: 22, govtResponse: 'Legislative inquiry opened into undisbursed 2020 funds' },
      { year: '2022', displaced: 1300000, damageNbn: 180, govtResponse: 'Federal emergency declared. IDP camps opened. World Bank support activated.' },
      { year: '2023', displaced: 520000, damageNbn: 41, govtResponse: 'State emergency fund. NEMA coordination.' },
      { year: '2024', displaced: 680000, damageNbn: 54, govtResponse: 'Emergency relief. No new permanent infrastructure commissioned.' },
    ],
  },

  health: {
    overview: 'Bayelsa\'s health crisis is quiet but deadly. With only 9% WASH access — versus 39% nationally — most residents drink contaminated water and defecate in the open. 62% of health facilities are non-functional. Maternal mortality is among Nigeria\'s highest. The state spends ₦28.3B on health but only 69% reaches intended programmes.',
    nationComparison: { label: 'Basic WASH access vs national avg', national: 39, bayelsa: 9, unit: '%' },
    lgaData: [
      { lga: 'Yenagoa',         washAccess: 28, functionalFacilities: 61, skilledBirth: 72, malariaCases: 3200 },
      { lga: 'Ogbia',           washAccess: 12, functionalFacilities: 42, skilledBirth: 54, malariaCases: 4100 },
      { lga: 'Brass',           washAccess: 4,  functionalFacilities: 28, skilledBirth: 38, malariaCases: 5200 },
      { lga: 'Nembe',           washAccess: 3,  functionalFacilities: 24, skilledBirth: 32, malariaCases: 4800 },
      { lga: 'Southern Ijaw',   washAccess: 2,  functionalFacilities: 19, skilledBirth: 28, malariaCases: 6100 },
      { lga: 'Kolokuma/Opokuma',washAccess: 9,  functionalFacilities: 38, skilledBirth: 48, malariaCases: 3600 },
      { lga: 'Ekeremor',        washAccess: 5,  functionalFacilities: 31, skilledBirth: 41, malariaCases: 4400 },
      { lga: 'Sagbama',         washAccess: 11, functionalFacilities: 44, skilledBirth: 55, malariaCases: 3800 },
    ],
    programs: [
      { name: 'Bayelsa Health Insurance Scheme', status: 'completed', budget: '₦8B', progress: 100, detail: 'State health insurance rolled out state-wide February 2023. Reduces out-of-pocket costs. One genuine win.' },
      { name: 'Primary Healthcare Revitalisation', status: 'partial', budget: '₦5.6B', progress: 45, detail: '127 PHCs rehabilitated of 290 total. 62% of health facilities still non-functional.' },
      { name: 'Bayelsa Specialist Hospital', status: 'ongoing', budget: '₦12B', progress: 55, detail: 'Federal Medical Centre Yenagoa expansion ongoing. Equipment procurement delays reported.' },
      { name: 'WASH Riverine Communities', status: 'not started', budget: 'Not funded', progress: 0, detail: 'No dedicated WASH programme for riverine communities exists despite 91% lacking basic access.' },
      { name: 'Free Malaria Treatment', status: 'ongoing', budget: '₦1.8B', progress: 75, detail: 'Free malaria testing and treatment in public facilities. Supply chain gaps mean frequent drug stockouts.' },
    ],
    keyFacts: [
      'Maternal mortality: ~1,200 per 100,000 live births — among Nigeria\'s highest',
      'Infant mortality: ~72 per 1,000 live births — nearly double the national target',
      'Only 38% of health facilities are functional — 290+ PHCs in various states of disrepair',
      'Doctor-to-patient ratio: 1:8,400 — WHO recommends 1:600',
      'Cholera outbreaks in Nembe and Brass LGAs annually due to contaminated water',
      '91% of residents lack basic sanitation — most rely on rivers for drinking water',
      'Skilled birth attendance at 52% — national target is 85%',
      'HIV prevalence: 3.4% — above national average of 1.4%',
    ],
    trend: [
      { year: '2020', wash: 6, facilities: 31, births: 44, budget: 18.2 },
      { year: '2021', wash: 7, facilities: 33, births: 46, budget: 21.4 },
      { year: '2022', wash: 7, facilities: 35, births: 49, budget: 24.1 },
      { year: '2023', wash: 8, facilities: 37, births: 51, budget: 26.8 },
      { year: '2024', wash: 9, facilities: 38, births: 52, budget: 28.3 },
    ],
  },

  environment: {
    overview: 'Bayelsa\'s environment is in crisis. 47 active oil spill sites have contaminated rivers and farmland across the state. The fishing economy — the primary livelihood for over 100,000 people in 6 LGAs — has collapsed. Shell (SPDC) is in the process of selling its onshore assets, raising fears communities will be abandoned without remediation. Governor Diri promised "zero active spill sites by 2025" at a September 2023 press conference. Zero have been remediated.',
    nationComparison: { label: 'Active oil spill sites per 1,000 km²', national: 1.2, bayelsa: 4.4, unit: 'sites' },
    lgaData: [
      { lga: 'Ogbia',           spillSites: 12, fishingImpact: 82, farmsAffected: 1800, remediated: 0 },
      { lga: 'Nembe',           spillSites: 9,  fishingImpact: 91, farmsAffected: 2100, remediated: 0 },
      { lga: 'Brass',           spillSites: 8,  fishingImpact: 78, farmsAffected: 1400, remediated: 0 },
      { lga: 'Southern Ijaw',   spillSites: 7,  fishingImpact: 69, farmsAffected: 1200, remediated: 0 },
      { lga: 'Sagbama',         spillSites: 5,  fishingImpact: 55, farmsAffected: 900,  remediated: 0 },
      { lga: 'Yenagoa',         spillSites: 3,  fishingImpact: 31, farmsAffected: 480,  remediated: 0 },
      { lga: 'Ekeremor',        spillSites: 2,  fishingImpact: 44, farmsAffected: 620,  remediated: 0 },
      { lga: 'Kolokuma/Opokuma',spillSites: 1,  fishingImpact: 18, farmsAffected: 210,  remediated: 0 },
    ],
    programs: [
      { name: 'Bayelsa Oil & Environmental Commission', status: 'partial', budget: '₦1.1B (of ₦4.2B)', progress: 12, detail: 'Commission exists but lacks enforcement power. No formal remediation orders issued against operators.' },
      { name: 'NOSDRA Coordination', status: 'partial', budget: 'Federal', progress: 20, detail: 'National Oil Spill Detection and Response Agency technically active. Severely underfunded and under-staffed.' },
      { name: 'Legal Action vs SPDC', status: 'partial', budget: '₦0 (legal costs)', progress: 10, detail: 'One ongoing court action. SPDC is selling onshore assets to Renaissance — communities fear no remediation transfer.' },
      { name: 'Gas Flaring Reduction', status: 'stalled', budget: 'Federal mandate', progress: 8, detail: 'Gas flaring in Bayelsa has reduced marginally but remains above GGFR targets. State has no enforcement role.' },
    ],
    keyFacts: [
      '47 active oil spill sites — zero remediated under Diri administration',
      '73% of oil pipelines crossing Bayelsa are past their technical service lifespan',
      'Shell (SPDC) sold onshore assets in 2024 to Renaissance — remediation responsibility uncertain',
      'Fishing communities in 6 LGAs report 70–90% decline in catch since early 2000s',
      'Gas flaring visible from satellite — Bayelsa among top 3 states for flaring intensity',
      'UNEP-style environmental assessment of Bayelsa has never been commissioned (Ogoniland got one)',
      'Groundwater contamination documented in Ogbia, Nembe — affecting drinking water of ~400,000 people',
      '₦1.1B of ₦4.2B allocated environment budget actually spent in FY2024 (26% execution)',
    ],
    spillHistory: [
      { year: '2020', newSpills: 8,  remediated: 0, affected: 28000 },
      { year: '2021', newSpills: 11, remediated: 0, affected: 34000 },
      { year: '2022', newSpills: 9,  remediated: 0, affected: 31000 },
      { year: '2023', newSpills: 12, remediated: 0, affected: 38000 },
      { year: '2024', newSpills: 7,  remediated: 0, affected: 26000 },
    ],
  },

  industry: {
    overview: 'Bayelsa sits on Nigeria\'s largest gas reserve — 18 trillion cubic feet — yet less than 8% of it is monetised. The state produces 23.4% of Nigeria\'s oil but has no downstream manufacturing. GDP ranks 11th nationally, but wealth is extracted, not retained. There is no published gas monetisation strategy, no special economic zone, and no significant non-oil industrial employer.',
    nationComparison: { label: 'Non-oil industry share of GDP', national: 18, bayelsa: 4, unit: '%' },
    lgaData: [
      { lga: 'Ogbia',        oilOutput: 34, gasOutput: 28, industrialJobs: 420, sezStatus: 'None' },
      { lga: 'Brass',        oilOutput: 22, gasOutput: 18, industrialJobs: 180, sezStatus: 'Proposed' },
      { lga: 'Nembe',        oilOutput: 19, gasOutput: 14, industrialJobs: 140, sezStatus: 'None' },
      { lga: 'Southern Ijaw',oilOutput: 14, gasOutput: 22, industrialJobs: 90,  sezStatus: 'None' },
      { lga: 'Sagbama',      oilOutput: 4,  gasOutput: 8,  industrialJobs: 210, sezStatus: 'None' },
      { lga: 'Yenagoa',      oilOutput: 2,  gasOutput: 3,  industrialJobs: 1840, sezStatus: 'Industrial Layout (stalled)' },
      { lga: 'Ekeremor',     oilOutput: 3,  gasOutput: 4,  industrialJobs: 80,  sezStatus: 'None' },
      { lga: 'Kolokuma',     oilOutput: 2,  gasOutput: 3,  industrialJobs: 120, sezStatus: 'None' },
    ],
    programs: [
      { name: 'Elebele Gas Turbine (60MW)', status: 'ongoing', budget: '₦45B', progress: 99, detail: '8 units of 60MW turbines installed. Missed December 2024 deadline. Tinubu inauguration pending.' },
      { name: 'Gas Monetisation Masterplan', status: 'not started', budget: 'Not budgeted', progress: 0, detail: 'No published strategy for Bayelsa\'s 18TCF gas reserve. The largest untapped opportunity in the state.' },
      { name: 'Brass LNG Terminal', status: 'stalled', budget: 'Federal/JV', progress: 12, detail: 'Federal LNG terminal project at Brass — stalled for over a decade due to funding disputes and JV disagreements.' },
      { name: 'Yenagoa Industrial Layout', status: 'stalled', budget: '₦4.4B', progress: 20, detail: 'Industrial estate announced years ago. No major tenant has commissioned. Infrastructure incomplete.' },
      { name: 'Blue Economy Initiative', status: 'partial', budget: '₦2.1B', progress: 25, detail: 'Aquaculture and maritime trade programme. Early stage — no major fishery or port development achieved.' },
    ],
    keyFacts: [
      'Bayelsa has 18 trillion cubic feet of gas — the largest gas reserve of any Nigerian state',
      'Less than 8% of this gas is currently monetised — mostly for domestic power generation',
      'State GDP: ₦4.63 trillion but oil contributes ~85% — non-oil sectors are tiny',
      'Brass LNG terminal — a $20B+ potential project — has been stalled for 15+ years',
      'Zero operational special economic zones or export processing zones',
      'Artisanal fishing is the largest non-oil employer — now severely degraded by oil spills',
      'No large non-government, non-oil employer exists in the state',
      'Tourism receipts estimated at <₦500M/year — a fraction of potential given beaches and eco-tourism assets',
    ],
    trend: [
      { year: '2020', oilPct: 88, nonOil: 2.8, gasMonetised: 5, gdp: 3.8 },
      { year: '2021', oilPct: 87, nonOil: 3.0, gasMonetised: 6, gdp: 4.1 },
      { year: '2022', oilPct: 86, nonOil: 3.0, gasMonetised: 6, gdp: 4.3 },
      { year: '2023', oilPct: 86, nonOil: 3.1, gasMonetised: 7, gdp: 4.5 },
      { year: '2024', oilPct: 85, nonOil: 3.1, gasMonetised: 8, gdp: 4.63 },
    ],
  },

  electricity: {
    overview: 'Bayelsa produces nearly a quarter of Nigeria\'s oil — yet its own residents get 4.2 hours of electricity per day. The flagship 300MW Bayelsa Power Company has stalled since August 2022 after consuming ₦8B+. The state sits on 18 trillion cubic feet of gas — enough to power the entire country — yet has no functional gas-to-power strategy. Rural electrification stands at 12% versus a 35% target.',
    nationComparison: { label: 'Avg daily power supply vs national avg', national: 8.6, bayelsa: 4.2, unit: 'hrs/day' },
    lgaData: [
      { lga: 'Yenagoa',         avgHours: 5.8, gridConnected: true,  solarProjects: 3, generatorDependency: 62 },
      { lga: 'Ogbia',           avgHours: 3.2, gridConnected: true,  solarProjects: 1, generatorDependency: 78 },
      { lga: 'Brass',           avgHours: 1.1, gridConnected: false, solarProjects: 0, generatorDependency: 96 },
      { lga: 'Nembe',           avgHours: 0.8, gridConnected: false, solarProjects: 0, generatorDependency: 98 },
      { lga: 'Southern Ijaw',   avgHours: 0.4, gridConnected: false, solarProjects: 1, generatorDependency: 99 },
      { lga: 'Kolokuma/Opokuma',avgHours: 2.8, gridConnected: true,  solarProjects: 0, generatorDependency: 81 },
      { lga: 'Ekeremor',        avgHours: 1.4, gridConnected: false, solarProjects: 0, generatorDependency: 94 },
      { lga: 'Sagbama',         avgHours: 3.1, gridConnected: true,  solarProjects: 1, generatorDependency: 76 },
    ],
    programs: [
      { name: 'Bayelsa Power Company (300MW)', status: 'stalled', budget: '₦60B (est)', progress: 35, detail: '₦8B+ consumed. Stalled since August 2022 — contractor dispute. No resolution after 2+ years. Biggest power failure of the administration.' },
      { name: '60MW Gas Turbine, Elebele', status: 'ongoing', budget: '₦45B', progress: 99, detail: '8x60MW units installed. Missed December 2024 deadline. President Tinubu expected to inaugurate. First tangible electricity win.' },
      { name: 'Imiringi Turbine Refurbishment', status: 'completed', budget: '₦2.1B', progress: 100, detail: 'Refurbishment completed August 2021. Added limited capacity to state grid — now operational.' },
      { name: 'Rural Solar Electrification', status: 'partial', budget: '₦3.8B', progress: 28, detail: '14 communities received solar installations. 3 of 5 riverine-focused projects still pending.' },
      { name: 'REA Grid Extension', status: 'partial', budget: 'Federal', progress: 30, detail: 'Federal Rural Electrification Agency extending grid to Kolokuma and Sagbama LGAs. Slow progress.' },
    ],
    keyFacts: [
      'Bayelsa produces 23.4% of Nigeria\'s oil — but its residents get 4.2hrs of power per day',
      'Bayelsa Power Company (300MW) has consumed ₦8B+ and has been stalled since August 2022',
      'Generators cost Bayelsa businesses and households an estimated ₦40B/year in fuel costs',
      'Hospitals in riverine LGAs use kerosene lamps for nighttime deliveries',
      'Rural electrification: 12% of target population covered — vs 35% national target for oil states',
      'Brass, Nembe, and Southern Ijaw LGAs have <1hr of grid power per day on average',
      'The 18TCF gas reserve could power all of Bayelsa for centuries — but no state gas-to-power strategy exists',
      'NERC Q3 2024 ranks Bayelsa among the 5 worst-served states for electricity in Nigeria',
    ],
    trend: [
      { year: '2020', avgHours: 3.4, ruralElec: 8,  projects: 0, budget: 9.1 },
      { year: '2021', avgHours: 3.6, ruralElec: 9,  projects: 1, budget: 12.4 },
      { year: '2022', avgHours: 3.8, ruralElec: 10, projects: 1, budget: 14.8 },
      { year: '2023', avgHours: 4.0, ruralElec: 11, projects: 1, budget: 16.1 },
      { year: '2024', avgHours: 4.2, ruralElec: 12, projects: 2, budget: 18.5 },
    ],
  },
}

// ── PRIORITIES ───────────────────────────────────────────────────────────────

export const PRIORITIES = [
  {
    rank: 1, urgency: 'URGENT',
    sector: 'Electricity', icon: '⚡',
    title: 'Resolve the Bayelsa Power Company dispute — now',
    why: 'The 300MW project has consumed ₦8B+ and has been stalled since August 2022 with no resolution. Hospitals, schools, and businesses run on generators. Every month of delay costs the economy more than fixing it would.',
    action: 'Issue a final 30-day ultimatum to contractors. If unresolved, terminate, pursue damages, and re-tender transparently. Publish a live weekly status update.',
    impact: 'Unlocks SME growth, reduces healthcare generator costs, enables schools to function after dark.',
    cost: '₦0 additional — existing ₦8B already committed',
    color: '#C97400',
  },
  {
    rank: 2, urgency: 'URGENT',
    sector: 'Flood Control', icon: '🌊',
    title: 'Commission a 10-year flood infrastructure masterplan',
    why: '1.3M+ people were displaced in the 2022 floods alone. Two-thirds of Bayelsa floods for 3+ months annually. Every road built without flood-proofing is destroyed within 18 months — making all infrastructure investment near-zero ROI.',
    action: 'Engage World Bank and AfDB for a phased ₦25B flood control investment. Begin Yenagoa drainage works Q3 2025. Mandate flood-proofing clauses in all road contracts.',
    impact: 'Protects existing road investments. Reduces annual displacement. Saves ₦12B+ in repeated emergency repairs.',
    cost: '₦25B over 10 years (fundable via World Bank / AfDB)',
    color: '#1B4FC4',
  },
  {
    rank: 3, urgency: 'HIGH',
    sector: 'Environment', icon: '🌿',
    title: 'Establish the Bayelsa Remediation Agency (BARA)',
    why: '47 active oil spill sites. Zero remediated in 5 years. The fishing economy — the primary livelihood for communities in 6 LGAs — has collapsed. 73% of pipelines are past their technical lifespan and more spills are inevitable.',
    action: 'Create BARA by executive order. Fund via 2% of FAAC allocation. Pursue Shell, Agip, and NAOC under Nigerian law for mandatory remediation. Begin Nembe in 2025.',
    impact: 'Restores fishing livelihoods for 100,000+ residents. Prevents groundwater contamination of drinking sources.',
    cost: '₦7.6B/year (recoverable via oil company liability suits)',
    color: '#008751',
  },
  {
    rank: 4, urgency: 'HIGH',
    sector: 'Health & WASH', icon: '🏥',
    title: 'Emergency WASH programme for riverine communities',
    why: 'Only 9% of Bayelsa residents have basic water or sanitation — vs. 39% nationally. Children are dying from preventable waterborne diseases. Maternal mortality is among Nigeria\'s highest.',
    action: 'Partner with UNICEF for a 3-year riverine WASH push. Digitise health facility reporting. Create midwife incentive scheme for rural postings. Rehabilitate the 62% of non-functional health facilities.',
    impact: 'Prevents thousands of preventable deaths annually. Reduces maternal mortality. Cuts school absenteeism from illness.',
    cost: '₦5B/year (co-funded with UNICEF and World Bank)',
    color: '#B50000',
  },
  {
    rank: 5, urgency: 'HIGH',
    sector: 'Economy / IGR', icon: '📈',
    title: 'Digitise tax collection — adopt the Lagos IGR model',
    why: 'IGR stands at ₦15.3B against a ₦28B target — a 45% shortfall. Bayelsa is 96% oil-dependent. When global oil demand declines, the state has no fallback. Lagos collects ₦1.8T IGR annually from a comparable economic base.',
    action: 'Deploy LIRS-style digital tax platform. Enforce IPPIS for all state employees. Set a public quarterly IGR scorecard. Target ₦25B IGR by 2026.',
    impact: 'Reduces oil dependency. Funds services without federal handouts. Builds a sustainable fiscal base past the oil era.',
    cost: '₦2B setup (one-time); self-funding within 18 months',
    color: '#6B3FA0',
  },
  {
    rank: 6, urgency: 'MEDIUM',
    sector: 'Roads', icon: '🛣️',
    title: 'Moratorium on new road groundbreakings',
    why: 'Six major road projects are active simultaneously. Most are behind schedule. New launches are announced before existing ones complete — spreading contractors, funding, and oversight too thin. The Yenagoa–Oporoma road is 2 years overdue.',
    action: 'Freeze all new road groundbreakings until 80% of current projects reach completion. Publish a live projects dashboard. Switch to milestone-based contractor payments.',
    impact: 'Concentrates resources. Delivers completions faster. Rebuilds public trust in government promises.',
    cost: '₦0 — this is a policy decision, not a spending line',
    color: '#7A8799',
  },
]

export const GOVERNOR_WINS = [
  { label: 'Vanguard Good Governance Award 2024', detail: 'Recognised for infrastructure, healthcare, education, and sports development.', icon: '🏅' },
  { label: 'Salary Arrears Cleared', detail: 'Cleared all inherited salary and pension arrears from the previous administration.', icon: '✅' },
  { label: 'Angiama Bridge (85% complete)', detail: 'Near-completion connectivity breakthrough for isolated Southern Ijaw communities.', icon: '🌉' },
  { label: '60MW Gas Turbine (99%)', detail: 'Near-complete power plant at Elebele — Tinubu set to inaugurate. Tangible electricity milestone.', icon: '⚡' },
  { label: 'Bayelsa Health Insurance', detail: 'Expanded state health insurance scheme — reducing out-of-pocket costs for residents.', icon: '🏥' },
  { label: '2025 Budget: ₦690B', detail: '"Assured Prosperity" budget — largest in state history. 2026 approaching ₦1 trillion.', icon: '📈' },
  { label: 'Tech Colleges in Every LGA', detail: 'Vocational colleges under construction in all 8 LGAs — skills-first education approach.', icon: '🎓' },
  { label: 'Sports Dominance', detail: 'Bayelsa Queens NWFL champions. Team Bayelsa tops NSF 2025. Cash rewards for athletes.', icon: '🥇' },
]
